### ISSUE TITLE
"Tous les Emplois" Error

### ISSUE THREAD

**Issue by houssembenhmida** [thevpc/vr#70]
Error when selecting "Tous les Emplois"(calandars plugin:UserWeekCalendarsCtrl): redirect to CMS
Error log:
25-Jul-2020 12:27:11.088 SEVERE [http-nio-8080-exec-46] net.vpc.upa.impl.config.DefaultUPAContext.invoke InvokeFailed
 java.lang.NullPointerException
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider$1.run(AcademicCalendarProvider.java:33)
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider$1.run(AcademicCalendarProvider.java:30)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invokePrivileged(DefaultUPAContext.java:337)
	at net.vpc.upa.impl.DefaultPersistenceUnit.invokePrivileged(DefaultPersistenceUnit.java:2841)
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider.retainUsersWithPublicWeekCalendars(AcademicCalendarProvider.java:30)
	at net.vpc.app.vainruling.plugins.calendars.service.CalendarsPlugin.lambda$findUsersWithPublicWeekCalendars$4(CalendarsPlugin.java:256)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invokePrivileged(DefaultUPAContext.java:337)
	at net.vpc.upa.impl.DefaultPersistenceUnit.invokePrivileged(DefaultPersistenceUnit.java:2841)
	at net.vpc.app.vainruling.plugins.calendars.service.CalendarsPlugin.findUsersWithPublicWeekCalendars(CalendarsPlugin.java:249)
	at net.vpc.app.vainruling.plugins.calendars.web.week.UserWeekCalendarsCtrl.onChangeUserType(UserWeekCalendarsCtrl.java:69)
	at net.vpc.app.vainruling.plugins.calendars.web.week.UserWeekCalendarsCtrl.onRefresh(UserWeekCalendarsCtrl.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.vpc.app.vainruling.core.service.util.PlatformReflector$DefaultMethodInvoker.invoke(PlatformReflector.java:380)
	at net.vpc.app.vainruling.core.service.util.PlatformReflector$DefaultInstanceInvoker.invoke(PlatformReflector.java:324)
	at net.vpc.app.vainruling.core.service.menu.VrServiceMenu.prepareGoto(VrServiceMenu.java:532)
	at net.vpc.app.vainruling.core.service.menu.VrServiceMenu.gotoPage(VrServiceMenu.java:710)
	at net.vpc.app.vainruling.core.web.menu.VrMenuManager.gotoPage(VrMenuManager.java:82)
	at net.vpc.app.vainruling.core.web.menu.VrMenuManager.gotoPage(VrMenuManager.java:70)
	at net.vpc.app.vainruling.core.web.jsf.Vr.gotoPage(Vr.java:892)
	at net.vpc.app.vainruling.core.web.jsf.ctrl.PageServlet.doGet(PageServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.app.vainruling.core.web.srv.VrWebSecurityFilter.doFilter(VrWebSecurityFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.app.vainruling.core.web.srv.TokenManagerFilter.doFilter(TokenManagerFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:237)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:214)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.upa.web.UPAServletRequestFilter$1.run(UPAServletRequestFilter.java:83)
	at net.vpc.upa.impl.config.VoidActionAdapter.run(VoidActionAdapter.java:24)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:345)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:461)
	at net.vpc.upa.web.UPAServletRequestFilter.doFilter(UPAServletRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

25-Jul-2020 12:27:11.090 SEVERE [http-nio-8080-exec-46] net.vpc.upa.impl.config.DefaultUPAContext.invoke InvokeFailed
 java.lang.NullPointerException
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider$1.run(AcademicCalendarProvider.java:33)
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider$1.run(AcademicCalendarProvider.java:30)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invokePrivileged(DefaultUPAContext.java:337)
	at net.vpc.upa.impl.DefaultPersistenceUnit.invokePrivileged(DefaultPersistenceUnit.java:2841)
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider.retainUsersWithPublicWeekCalendars(AcademicCalendarProvider.java:30)
	at net.vpc.app.vainruling.plugins.calendars.service.CalendarsPlugin.lambda$findUsersWithPublicWeekCalendars$4(CalendarsPlugin.java:256)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invokePrivileged(DefaultUPAContext.java:337)
	at net.vpc.upa.impl.DefaultPersistenceUnit.invokePrivileged(DefaultPersistenceUnit.java:2841)
	at net.vpc.app.vainruling.plugins.calendars.service.CalendarsPlugin.findUsersWithPublicWeekCalendars(CalendarsPlugin.java:249)
	at net.vpc.app.vainruling.plugins.calendars.web.week.UserWeekCalendarsCtrl.onChangeUserType(UserWeekCalendarsCtrl.java:69)
	at net.vpc.app.vainruling.plugins.calendars.web.week.UserWeekCalendarsCtrl.onRefresh(UserWeekCalendarsCtrl.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.vpc.app.vainruling.core.service.util.PlatformReflector$DefaultMethodInvoker.invoke(PlatformReflector.java:380)
	at net.vpc.app.vainruling.core.service.util.PlatformReflector$DefaultInstanceInvoker.invoke(PlatformReflector.java:324)
	at net.vpc.app.vainruling.core.service.menu.VrServiceMenu.prepareGoto(VrServiceMenu.java:532)
	at net.vpc.app.vainruling.core.service.menu.VrServiceMenu.gotoPage(VrServiceMenu.java:710)
	at net.vpc.app.vainruling.core.web.menu.VrMenuManager.gotoPage(VrMenuManager.java:82)
	at net.vpc.app.vainruling.core.web.menu.VrMenuManager.gotoPage(VrMenuManager.java:70)
	at net.vpc.app.vainruling.core.web.jsf.Vr.gotoPage(Vr.java:892)
	at net.vpc.app.vainruling.core.web.jsf.ctrl.PageServlet.doGet(PageServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.app.vainruling.core.web.srv.VrWebSecurityFilter.doFilter(VrWebSecurityFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.app.vainruling.core.web.srv.TokenManagerFilter.doFilter(TokenManagerFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:237)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:214)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.upa.web.UPAServletRequestFilter$1.run(UPAServletRequestFilter.java:83)
	at net.vpc.upa.impl.config.VoidActionAdapter.run(VoidActionAdapter.java:24)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:345)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:461)
	at net.vpc.upa.web.UPAServletRequestFilter.doFilter(UPAServletRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

25-Jul-2020 12:27:11.091 SEVERE [http-nio-8080-exec-46] net.vpc.app.vainruling.core.web.srv.VrWebSecurityFilter.doFilter Unhandled Error
 java.lang.NullPointerException
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider$1.run(AcademicCalendarProvider.java:33)
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider$1.run(AcademicCalendarProvider.java:30)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invokePrivileged(DefaultUPAContext.java:337)
	at net.vpc.upa.impl.DefaultPersistenceUnit.invokePrivileged(DefaultPersistenceUnit.java:2841)
	at net.vpc.app.vainruling.plugins.academic.planning.service.callbacks.AcademicCalendarProvider.retainUsersWithPublicWeekCalendars(AcademicCalendarProvider.java:30)
	at net.vpc.app.vainruling.plugins.calendars.service.CalendarsPlugin.lambda$findUsersWithPublicWeekCalendars$4(CalendarsPlugin.java:256)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invokePrivileged(DefaultUPAContext.java:337)
	at net.vpc.upa.impl.DefaultPersistenceUnit.invokePrivileged(DefaultPersistenceUnit.java:2841)
	at net.vpc.app.vainruling.plugins.calendars.service.CalendarsPlugin.findUsersWithPublicWeekCalendars(CalendarsPlugin.java:249)
	at net.vpc.app.vainruling.plugins.calendars.web.week.UserWeekCalendarsCtrl.onChangeUserType(UserWeekCalendarsCtrl.java:69)
	at net.vpc.app.vainruling.plugins.calendars.web.week.UserWeekCalendarsCtrl.onRefresh(UserWeekCalendarsCtrl.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.vpc.app.vainruling.core.service.util.PlatformReflector$DefaultMethodInvoker.invoke(PlatformReflector.java:380)
	at net.vpc.app.vainruling.core.service.util.PlatformReflector$DefaultInstanceInvoker.invoke(PlatformReflector.java:324)
	at net.vpc.app.vainruling.core.service.menu.VrServiceMenu.prepareGoto(VrServiceMenu.java:532)
	at net.vpc.app.vainruling.core.service.menu.VrServiceMenu.gotoPage(VrServiceMenu.java:710)
	at net.vpc.app.vainruling.core.web.menu.VrMenuManager.gotoPage(VrMenuManager.java:82)
	at net.vpc.app.vainruling.core.web.menu.VrMenuManager.gotoPage(VrMenuManager.java:70)
	at net.vpc.app.vainruling.core.web.jsf.Vr.gotoPage(Vr.java:892)
	at net.vpc.app.vainruling.core.web.jsf.ctrl.PageServlet.doGet(PageServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.app.vainruling.core.web.srv.VrWebSecurityFilter.doFilter(VrWebSecurityFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.app.vainruling.core.web.srv.TokenManagerFilter.doFilter(TokenManagerFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:237)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:214)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at net.vpc.upa.web.UPAServletRequestFilter$1.run(UPAServletRequestFilter.java:83)
	at net.vpc.upa.impl.config.VoidActionAdapter.run(VoidActionAdapter.java:24)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:408)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:345)
	at net.vpc.upa.impl.config.DefaultUPAContext.invoke(DefaultUPAContext.java:461)
	at net.vpc.upa.web.UPAServletRequestFilter.doFilter(UPAServletRequestFilter.java:80)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by thevpc** [comment]
On the deployed version (enis.info) or on premise ?

**Comment by houssembenhmida** [comment]
on premise.
PS: I didn't fill the database. It contains the default data only.
